name: Build SysML CLI (private, no publish)

on:
  workflow_dispatch:      # run manually

jobs:
  build-cli:
    runs-on: ubuntu-latest
    permissions: { contents: read }  # prevents pushes / releases

    steps:
      # 1️⃣ Full checkout (Gradle wrapper is at repo root)
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      # 2️⃣ Java 17 (Gradle build requires 17)
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      # 3️⃣ Build only the sysml-cli distribution (no publish)
      - name: Gradle installDist
        run: |
          ./gradlew :sysml-cli:installDist --no-daemon --warning-mode all

      # 4️⃣ Zip the distribution folder
      - name: Zip CLI
        run: |
          cd sysml-cli/build/install
          zip -r ${{ github.workspace }}/sysml-cli-dist.zip sysml-cli

      # 5️⃣ Upload artifact for private download (kept 7 days)
      - uses: actions/upload-artifact@v4
        with:
          name: sysml-cli-dist
          path: sysml-cli-dist.zip
          retention-days: 7
