name: Build SysML Interactive Jar (private)

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Maven package
        run: >
          mvn -B --projects org.omg.sysml.interactive --also-make
          -Dtycho.version=4.0.12 -DskipTests -Dmaven.deploy.skip=true
          clean package

      - name: Zip artifact
        run: |
          JAR=$(ls org.omg.sysml.interactive/target/org.omg.sysml.interactive-*-all.jar)
          mkdir dist && cp "$JAR" dist/sysml-interactive.jar
          (cd dist && zip -r ../sysml-interactive-dist.zip .)

      - uses: actions/upload-artifact@v4
        with:
          name: sysml-interactive-dist
          path: sysml-interactive-dist.zip
          retention-days: 7
