name: Build non-interactive SysML CLI

on: workflow_dispatch        # run manually

jobs:
  build-cli:
    runs-on: ubuntu-latest
    permissions: { contents: read }

    steps:
      # --- (A) checkout your fork (optional) ------------
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      # --- (B) shallow-clone the Gradle sub-repo --------
      - name: Clone pilot-impl sources
        run: |
          git clone --depth 1 https://github.com/Systems-Modeling/SysML-v2-Pilot-Implementation.git pilot-impl

      # --- (C) Java 17 for Gradle -----------------------
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      # --- (D) build only the CLI -----------------------
      - name: Gradle :sysml-cli:installDist
        working-directory: pilot-impl/sysml-cli
        run: ./gradlew installDist --no-daemon --warning-mode all

      # --- (E) zip the distribution ---------------------
      - name: Zip sysml-cli
        run: |
          cd pilot-impl/sysml-cli/build/install
          zip -r ${{ github.workspace }}/sysml-cli-dist.zip sysml-cli

      # --- (F) upload for private download --------------
      - uses: actions/upload-artifact@v4
        with:
          name: sysml-cli-dist
          path: sysml-cli-dist.zip
          retention-days: 7
